### ISSUE TITLE
What ist special to 6:28 CET?

### ISSUE THREAD

**Issue by khvolk** [khoih-prog/NTPClient_Generic#2]
I get a very special issue with NTClient_Generic. I am using an esp32 board (Doit devkit v1), PlatformIO with VSCode on a Manjaro Desktop. Running the example Ethernet_NTPClient_Advanced (WLAN-Mode) works normally well:

********UPDATED********
UTC : 10:54:20
UTC : 10:54:20 Sat 06 Mar 2021
LOC : 11:54:20
LOC : 11:54:20 Sat 06 Mar 2021
UTC EPOCH : 1615028060
LOC EPOCH : 1615031660
UTC : 10:54:20 Sat 6/3/2021 or 6 Mar 2021
UTC : 10:54:20 Sat 6/3/2021 or 6 Mar 2021
LOC : 11:54:20 Sat 6/3/2021 or 6 Mar 2021
LOC : 11:54:20 Sat 6/3/2021 or 6 Mar 2021

But in between, for some seconds or a minute I get once or twice a day:
********UPDATED********
UTC : 06:28:29
UTC : 06:28:29 Thu 07 Feb 2036
LOC : 07:28:29
LOC : 07:28:29 Thu 07 Feb 2036
UTC EPOCH : 2085978509
LOC EPOCH : 2085982109
UTC : 6:28:29 Thu 7/2/2036 or 7 Feb 2036
UTC : 06:28:29 Thu 7/2/2036 or 7 Feb 2036
LOC : 7:28:29 Thu 7/2/2036 or 7 Feb 2036
LOC : 07:28:29 Thu 7/2/2036 or 7 Feb 2036 

All the other times everything works fine. Any idea how this can happen? In this test program I am running

   timeClient.update(); 

every second. This happens since 10 days or so, since i set up a clock with this.

**Comment by khvolk** [comment]
I am using the Arduino framework but I plan to change to ESP-IDF.

**Comment by khoih-prog** [comment]
Thanks for using the library and it;s working so far.

I don't know what wrong now, just can guess some data got corrupted. It's possible the time server doesn't like the **too-frequent** access or **can't respond correctly.**

Can you try to change the `timeClient.update()` from **every second** to much longer time (**10s-30s**) and test.

**Comment by khvolk** [comment]
I put the timeClient.update() to 300s. Now the clock is 5 to 10 minutes late.

**Comment by khvolk** [comment]
I put the timeClient.update() to 300s. Now the clock is 5 to 10 minutes late.

**Comment by khvolk** [comment]
Did not want to close it. sorry.
