### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by bmcdonnell** [khoih-prog/NTPClient_Generic#5]
[Link to license](https://github.com/khoih-prog/NTPClient_Generic/blob/master/LICENSE) at the [bottom of the README](https://github.com/khoih-prog/NTPClient_Generic/tree/26f17747b86285040366b1a2605441bc5e54a7ee#license) is broken.

**Comment by khoih-prog** [comment]
Done.
Thanks for pointing out,
BR,
