### ISSUE TITLE
How to display the time in 24-hour format (military time)

### ISSUE THREAD

**Issue by corydoras09** [khoih-prog/NTPClient_Generic#6]

**Comment by khoih-prog** [comment]
Have a look at [**Debug Terminal Output Samples**](https://github.com/khoih-prog/NTPClient_Generic#debug-terminal-output-samples) and see that the time is displayed as `hh:mm:ss`

You can select to display any format you'd like, by converting it. If you don't know how to do, just research or post on Arduino Forum to ask for help.
