### ISSUE TITLE
getUTCEpochMillis() not returning correct value

### ISSUE THREAD

**Issue by DavidSteinmann** [khoih-prog/NTPClient_Generic#7]
The method getUTCEpochMillis() does not return the full 64 bits of the unsigned long long.
The compiler doesn't convert _currentEpoc to unsigned long long and discards all the bits after the 32-bit value when calculating.
I fixed this by explicitly casting _currentEpoc to unsigned long long.

Fix in NTPClient_Generic_Impl.h:
```
unsigned long long NTPClient::getUTCEpochMillis() 
{
  unsigned long long epoch;

  epoch  = (unsigned long long)this->_currentEpoc * 1000;                   // last time returned via server in millis
  epoch += (this->_currentFraction) / FRACTIONSPERMILLI;  // add the fraction from the server
  epoch += millis() - this->_lastUpdate;          // add the millis that have passed since the last update

  return epoch;
}
```

Additional Info:
```
IDE: Visual Studio 2022 with Visual Micro (with Arduino 1.6/1.8).
ESP32 Core Version:  1.0.6
Arduino IDE version: 1.8.19
OS: Windows 10 Home
```

**Comment by khoih-prog** [comment]
Hi @DavidSteinmann 

Thanks for spotting and reporting the bug.

I'll update the `master` then publish a new release soon, certainly with your contribution noted.

I'm looking forward to receiving more contributions from you.

Best Regards,

**Comment by khoih-prog** [comment]
Hi @DavidSteinmann 

The new [**NTPClient_Generic releases v3.7.1**](https://github.com/khoih-prog/NTPClient_Generic/releases/tag/v3.7.1) has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/NTPClient_Generic#contributions-and-thanks)

Best Regards,

---

### Releases v3.7.1

1. Fix getUTCEpochMillis() bug. Check [getUTCEpochMillis() not returning correct value #7](https://github.com/khoih-prog/NTPClient_Generic/issues/7)
2. Update Adafruit SAMD `Packages_Patches`
